(function(){
'use strict';
const bodies=new WeakMap();
const reduced=()=>document.body.classList.contains('low-motion')||matchMedia('(prefers-reduced-motion: reduce)').matches;
const num=(v,d=0)=>Number.isFinite(+v)?+v:d;
function sceneOf(el){return el.closest('.scene')||document.body}
function current(el){return{x:num(el.dataset.dragX),y:num(el.dataset.dragY),angle:num(el.dataset.physicsAngle)}}
function baseRect(el){const r=el.getBoundingClientRect(),c=current(el);return{left:r.left-c.x,top:r.top-c.y,right:r.right-c.x,bottom:r.bottom-c.y,width:r.width,height:r.height}}
function rectAt(el,x,y){const b=baseRect(el);return{left:b.left+x,top:b.top+y,right:b.right+x,bottom:b.bottom+y,width:b.width,height:b.height}}
function obstacleRects(el){return[...sceneOf(el).querySelectorAll('[data-physics-obstacle="1"]')].filter(x=>x!==el&&x.offsetParent!==null).map(x=>{const r=x.getBoundingClientRect(),pad=num(x.dataset.physicsObstaclePad,0);return{left:r.left-pad,top:r.top-pad,right:r.right+pad,bottom:r.bottom+pad,el:x}})}
function overlap(a,b){return a.right>b.left&&a.left<b.right&&a.bottom>b.top&&a.top<b.bottom}
function resolveObstacles(el,x,y){let nx=x,ny=y,hitX=false,hitY=false,hitEl=null;for(const o of obstacleRects(el)){let r=rectAt(el,nx,ny);if(!overlap(r,o))continue;const pushes=[{axis:'x',d:o.left-r.right},{axis:'x',d:o.right-r.left},{axis:'y',d:o.top-r.bottom},{axis:'y',d:o.bottom-r.top}].sort((a,b)=>Math.abs(a.d)-Math.abs(b.d));const p=pushes[0];if(p.axis==='x'){nx+=p.d;hitX=true}else{ny+=p.d;hitY=true}hitEl=o.el}return{x:nx,y:ny,hitX,hitY,hitEl}}
function constrain(el,x,y,pad=8){const scene=sceneOf(el),sr=scene.getBoundingClientRect(),er=el.getBoundingClientRect(),cur=current(el),base={left:er.left-cur.x,top:er.top-cur.y,right:er.right-cur.x,bottom:er.bottom-cur.y};let nx=x,ny=y,hitX=false,hitY=false;
  if(base.left+nx<sr.left+pad){nx=sr.left+pad-base.left;hitX=true}if(base.right+nx>sr.right-pad){nx=sr.right-pad-base.right;hitX=true}
  if(base.top+ny<sr.top+pad){ny=sr.top+pad-base.top;hitY=true}if(base.bottom+ny>sr.bottom-pad){ny=sr.bottom-pad-base.bottom;hitY=true}
  const o=resolveObstacles(el,nx,ny);return{x:o.x,y:o.y,hitX:hitX||o.hitX,hitY:hitY||o.hitY,hitEl:o.hitEl};
}
function apply(el,x,y,vx=0,vy=0,angle=null){el.dataset.dragX=x.toFixed(2);el.dataset.dragY=y.toFixed(2);el.style.setProperty('--drag-x',`${x.toFixed(2)}px`);el.style.setProperty('--drag-y',`${y.toFixed(2)}px`);const a=angle===null?Math.max(-7,Math.min(7,vx*.018)):angle;el.dataset.physicsAngle=Number(a).toFixed(2);el.style.setProperty('--physics-r',`${Number(a).toFixed(2)}deg`);el.dispatchEvent(new CustomEvent('gswphysicsmove',{detail:{x,y,vx,vy,angle:a},bubbles:false}))}
function cancel(el){const b=bodies.get(el);if(b?.raf)cancelAnimationFrame(b.raf);bodies.delete(el);el.classList.remove('v101-inertia','v101-collision','v101-spring');el.style.removeProperty('--physics-r')}
function release(el,d={}){cancel(el);if(reduced()||el.dataset.physicsFree!=='1')return;let {x,y,angle}=current(el);let vx=num(d.vx)*930,vy=num(d.vy)*930;const mass=Math.max(.35,num(el.dataset.physicsMass,1));vx/=Math.sqrt(mass);vy/=Math.sqrt(mass);if(Math.hypot(vx,vy)<38)return;const restitution=Math.max(.08,Math.min(.72,num(el.dataset.physicsBounce,.28))),friction=Math.max(.86,Math.min(.994,num(el.dataset.physicsFriction,.945))),angularFriction=Math.max(.80,Math.min(.995,num(el.dataset.physicsAngularFriction,.92)));const gravity=num(el.dataset.physicsGravity,0),spin=num(el.dataset.physicsSpin,.018);let omega=(vx*.015-vy*.007)*spin*55;const body={raf:0,last:performance.now(),vx,vy,x,y,angle,omega};bodies.set(el,body);el.classList.add('v101-inertia');
 const step=t=>{if(bodies.get(el)!==body||!el.isConnected){cancel(el);return}const dt=Math.min(.034,Math.max(.008,(t-body.last)/1000));body.last=t;body.vy+=gravity*dt;body.x+=body.vx*dt;body.y+=body.vy*dt;body.angle+=body.omega*dt;const c=constrain(el,body.x,body.y,8);let hit=false;if(c.hitX||Math.abs(c.x-body.x)>.1){body.x=c.x;body.vx*=-restitution;body.omega+=body.vy*.012;hit=true}if(c.hitY||Math.abs(c.y-body.y)>.1){body.y=c.y;body.vy*=-restitution;body.omega-=body.vx*.010;hit=true}if(hit){el.classList.add('v101-collision');el.dispatchEvent(new CustomEvent('gswphysicscollision',{detail:{obstacle:c.hitEl||null,vx:body.vx,vy:body.vy},bubbles:false}));setTimeout(()=>el.classList.remove('v101-collision'),90)}const decay=Math.pow(friction,dt*60),adecay=Math.pow(angularFriction,dt*60);body.vx*=decay;body.vy*=decay;body.omega*=adecay;body.angle=Math.max(-10,Math.min(10,body.angle));apply(el,body.x,body.y,body.vx,body.vy,body.angle);if(Math.hypot(body.vx,body.vy)<13&&Math.abs(body.omega)<2){cancel(el);el.style.removeProperty('--physics-r');return}body.raf=requestAnimationFrame(step)};body.raf=requestAnimationFrame(step)
}
function spring(el,x=0,y=0,ms=360){cancel(el);if(reduced()){apply(el,x,y,0,0,0);return}const start=current(el),t0=performance.now(),body={raf:0,type:'spring'};bodies.set(el,body);el.classList.add('v101-spring');const tick=t=>{if(bodies.get(el)!==body||!el.isConnected)return;const q=Math.min(1,(t-t0)/ms),e=1-Math.exp(-7*q)*Math.cos(10*q),nx=start.x+(x-start.x)*e,ny=start.y+(y-start.y)*e,a=(1-q)*start.angle*.45;apply(el,nx,ny,0,0,a);if(q<1)body.raf=requestAnimationFrame(tick);else{apply(el,x,y,0,0,0);bodies.delete(el);el.classList.remove('v101-spring');el.style.removeProperty('--physics-r')}};body.raf=requestAnimationFrame(tick)}
window.GSW_PHYSICS={version:'10.3.0',cancel,constrain,release,spring,current,obstacles:obstacleRects};
})();
