(function(){
'use strict';
let current=null,raf=0,tx=0,ty=0,cx=0,cy=0;
function labelFor(el){return (el.getAttribute('aria-label')||el.dataset.label||el.textContent||'检查').replace(/\s+/g,' ').trim().slice(0,28)}
function hotspot(el){if(!el||el.classList.contains('outcome-prop')||el.classList.contains('return-tab')||el.classList.contains('v8-hotspot'))return;el.classList.add('v8-hotspot');if(getComputedStyle(el).position==='static')el.style.position='relative';const ring=document.createElement('i');ring.className='v8-hotspot-ring';ring.setAttribute('aria-hidden','true');ring.style.left='50%';ring.style.top='50%';el.appendChild(ring);const lab=document.createElement('span');lab.className='v8-object-label';lab.textContent=labelFor(el);el.appendChild(lab);}
function actionScene(scene){scene.querySelectorAll('button,[role="button"],.prop,.anomaly,.evidence,.sound-node').forEach(hotspot);const outs=scene.querySelector('.outcomes');if(outs){const refine=()=>outs.querySelectorAll('.outcome-prop').forEach((b,i)=>{b.setAttribute('aria-label',b.textContent.trim());b.dataset.v8Choice=String(i+1)});new MutationObserver(refine).observe(outs,{childList:true,subtree:true});refine();}}
function decorate(){const s=document.querySelector('.scene');if(!s||s===current)return;current=s;cancelAnimationFrame(raf);tx=ty=cx=cy=0;const art=s.querySelector('.scene-art');if(art&&!s.querySelector('.v8-depth-copy')){const copy=art.cloneNode();copy.className='v8-depth-copy';copy.setAttribute('aria-hidden','true');s.insertBefore(copy,art.nextSibling);const glass=document.createElement('i');glass.className='v8-camera-glass';glass.setAttribute('aria-hidden','true');s.appendChild(glass)}actionScene(s);const move=e=>{if(document.body.classList.contains('low-motion'))return;const r=s.getBoundingClientRect();tx=(e.clientX-r.left)/r.width-.5;ty=(e.clientY-r.top)/r.height-.5};s.addEventListener('pointermove',move,{passive:true});s.addEventListener('pointerleave',()=>{tx=ty=0});function tick(){cx+=(tx-cx)*.07;cy+=(ty-cy)*.07;s.style.setProperty('--v8-x',cx.toFixed(4));s.style.setProperty('--v8-y',cy.toFixed(4));raf=requestAnimationFrame(tick)}tick();new MutationObserver(()=>{if(s.querySelector('.scene-resolution'))s.classList.add('v8-resolving');actionScene(s)}).observe(s,{childList:true,subtree:true});}
new MutationObserver(decorate).observe(document.getElementById('app'),{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',decorate);else decorate();window.addEventListener('beforeunload',()=>cancelAnimationFrame(raf));
})();
